name: Build CI

on: pull_request
env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_USERNAME: ${{ github.actor }}
  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_IMAGE_NAME: ${{ github.repository }}-${{ github.sha }}

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.15.0
        cache: yarn

    - name: Installing dependencies
      run: yarn

    - name: Linting
      run: yarn lint

  test:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.15.0
        cache: yarn

    - name: Installing dependencies
      run: yarn

    - name: Running tests
      run: yarn test

# TODO: add build job
