on:
  push:
    branches:
      - master
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - id: release
        name: release
        uses: google-github-actions/release-please-action@v3
        name: release
        with:
          release-type: node
          package-name: test-release-please
      - id: checkout
        name: checkout
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v2
      - id: automerge
        name: automerge
        if: ${{ steps.release.outputs.release_created }}
        uses: "pascalgn/automerge-action@v0.15.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PULL_REQUEST: ${{ steps.release.outputs.pr }}
