on:
  push:
    branches:
      - master
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        name: release
        with:
          release-type: node
          package-name: test-release-please
      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}
      - uses: "pascalgn/automerge-action@v0.15.3"
        id: automerge
        name: merge
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PULL_REQUEST: ${{ steps.release.outputs.pr }}
